### ISSUE TITLE
AirFreshStatus object has no attribute 'ptc' on zhimi.airfresh.va4

### ISSUE THREAD

**Issue by AntoxaSa** [syssi/xiaomi_airpurifier#88]
problem, breather zhimi.airfresh.va4 does not appear in objects after being written in the configuration file

**Comment by syssi** [comment]
Please take a look at your `home-assistant.log` and provide the regarding error message.

**Comment by AntoxaSa** [comment]
Can't login to MiCloud
21:06:24 – Xiaomi Gateway 3 (ERROR)
Can't login to Mi Cloud: Expecting value: line 1 column 1 (char 0)
21:06:24 – Xiaomi Gateway 3 (ERROR)
Timeout while loading MiCloud device list
21:06:24 – Xiaomi Gateway 3 (ERROR)
Invalid fan_modes mode: QUIET
21:06:15 – MQTT (ERROR) - первое сообщение получено 21:06:14 и повторялось 4 раз
xiaomi_miio_airpurifier: Error on device update!
21:06:14 – Вентилятор (ERROR)
The 'entity_id' option is deprecated, please remove it from your configuration
21:05:56 – template (WARNING) - первое сообщение получено 21:05:56 и повторялось 5 раз
You are using a custom integration for gismeteo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
21:05:55 – loader.py (WARNING) - первое сообщение получено 21:05:55 и повторялось 2 раз
Уровень: ERROR
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:958
Integration: Вентилятор (documentation, issues)
First occurred: 21:06:14 (1 occurrences)
Last logged: 21:06:14

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1636, in async_update
    {
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1637, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 958, in _extract_value_from_attribute
    value = getattr(state, attribute)
AttributeError: 'AirFreshStatus' object has no attribute 'ptc'

**Comment by AntoxaSa** [comment]
![airfrash](https://user-images.githubusercontent.com/71827946/97808227-87d55580-1c87-11eb-811f-08215be68354.jpg)

**Comment by AntoxaSa** [comment]
![airfrash](https://user-images.githubusercontent.com/71827946/97808475-e64f0380-1c88-11eb-8e98-41c2f8ee655e.jpg)

**Comment by syssi** [comment]
@AntoxaSa Please remove the line

```
model: zhimi.airfresh.va4
```

of your `configuration.yaml`. Are you sure your device model is  a `zhimi.airfresh.va4`?

**Comment by syssi** [comment]
My be it's an `zhimi.airfresh.va2` without a ptc?

**Comment by AntoxaSa** [comment]
I just have a new model with heating Va4. I tried to prescribe how VA2 works there are no errors, but there is no heating in the settings.

**Comment by AntoxaSa** [comment]
![airfrash2](https://user-images.githubusercontent.com/71827946/97809432-a428c080-1c8e-11eb-94e1-258560c74907.jpg)

**Comment by syssi** [comment]
`ptc` is the attribute/status of the external heater. Do you have a linux host and are you able to do a few miiocli calls to debug the issue?

**Comment by AntoxaSa** [comment]
I have a raspberry and it has Home Assistant. Tell me how to make calls for debugging.

**Comment by syssi** [comment]
```
# install python-miio
pip3 install python-miiio

# call miiocli and retrieve a single property ("ptc_state")
miiocli device --ip IP --token TOKEN raw_command get_prop '["ptc_state"]'

# call miiocli and retrieve the last bunch of properties
miiocli device --ip IP --token TOKEN raw_command get_prop '["filter_life", "f_hour", "favorite_level", "led", "ptc_state"]'

# call miiocli and retrieve the first bunch of properties
miiocli device --ip IP --token TOKEN raw_command get_prop '["power", "temp_dec", "aqi", "average_aqi", "co2", "buzzer", "child_lock", "humidity", "led_level", "mode", "motor1_speed", "use_time", "ntcT", "app_extra", "f1_hour_used"]'

# call miiocli and retrieve more than 15 properties
miiocli device --ip IP --token TOKEN raw_command get_prop '["power", "temp_dec", "aqi", "average_aqi", "co2", "buzzer", "child_lock", "humidity", "led_level", "mode", "motor1_speed", "use_time", "ntcT", "app_extra", "f1_hour_used", "filter_life", "f_hour", "favorite_level", "led", "ptc_state"]'
```

**Comment by AntoxaSa** [comment]
does it need to be done in windows command line or in razbery?

**Comment by syssi** [comment]
`pip3` is the package manage of python3. This should be installed on your raspberry pi. If you install python + pip on your windows host, you can also make these calls on your windows host. `miiocli` is a executable provided by `python-miio` installed by `pip3 install python-miio`.

**Comment by AntoxaSa** [comment]
find the problem? do you still need to debug?

**Comment by syssi** [comment]
Yes. I need the responses of the `miiocli` calls. I assume it's a bug but I cannot solve it without your feedback.

**Comment by AntoxaSa** [comment]
it doesn't work. Doesn't accept commands (What am I doing wrong?
![comand](https://user-images.githubusercontent.com/71827946/97811007-92004f80-1c99-11eb-8e9f-a2c521b1b382.jpg)

**Comment by AntoxaSa** [comment]
pip3 install python-miiio - command not found

**Comment by syssi** [comment]
It looks like `pip` isn't installed:

```
apt-get update
apt-get install python3-pip
pip3 install python-miio
miiocli...
```

**Comment by AntoxaSa** [comment]
antoxa@raspberrypi:~ $ sudo miiocli device --ip 192.168.2.114 --token 22c43c60c2beb41380e7e118b17189f7 raw_command get_prop '["ptc_state"]'
Running command raw_command
['on']

antoxa@raspberrypi:~ $ sudo miiocli device --ip 192.168.2.114 --token 22c43c60c2beb41380e7e118b17189f7 raw_command get_prop '["filter_life", "f_hour", "favorite_level", "led", "ptc_state"]'
Running command raw_command
[None, None, None, None, 'on']


antoxa@raspberrypi:~ $ sudo miiocli device --ip 192.168.2.114 --token 22c43c60c2beb41380e7e118b17189f7 raw_command get_prop '["power", "temp_dec", "aqi", "average_aqi", "co2", "buzzer", "child_lock", "humidity", "led_level", "mode", "motor1_speed", "use_time", "ntcT", "app_extra", "f1_hour_used"]'
Running command raw_command
['on', 20.9, 1, 1, 608, 'on', 'off', 44, 0, 'silent', 399, 2045100, 19.52, None, 568]


antoxa@raspberrypi:~ $ sudo miiocli device --ip 192.168.2.114 --token 22c43c60c2beb41380e7e118b17189f7 raw_command get_prop '["power", "temp_dec", "aqi", "average_aqi", "co2", "buzzer", "child_lock", "humidity", "led_level", "mode", "motor1_speed", "use_time", "ntcT", "app_extra", "f1_hour_used", "filter_life", "f_hour", "favorite_level", "led", "ptc_state"]'
Running command raw_command
['on', 20.9, 1, 1, 603, 'on', 'off', 44, 0, 'silent', 399, 2045100, 18.69, None, 568, None]

antoxa@raspberrypi:~ $ sudo miiocli device --ip 192.168.2.114 --token 22c43c60c2beb41380e7e118b17189f7 info
Model: zhimi.airfresh.va4
Hardware version: MW300
Firmware version: 1.4.6_1014
Network: {'localIp': '192.168.2.114', 'mask': '255.255.255.0', 'gw': '192.168.2.1', 'gw_mac':                        'EC:43:F6:D7:B3:FA'}
AP: {'rssi': -45, 'ssid': 'Monstr174', 'bssid': 'EC:43:F6:D7:B3:FA'}

**Comment by syssi** [comment]
I know what happend. Thanks for your report! The `develop` branch is fixed now.

**Comment by AntoxaSa** [comment]
It still doesn't work. Updated to 6.1
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:960
Integration: Вентилятор (documentation, issues)
First occurred: 0:32:48 (1 occurrences)
Last logged: 0:32:48

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1638, in async_update
    {
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1639, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 960, in _extract_value_from_attribute
    value = getattr(state, attribute)
AttributeError: 'AirFreshStatus' object has no attribute 'ptc'

**Comment by syssi** [comment]
Release 0.6.1 doesn't contain the fix. Please install the `develop` version.

**Comment by AntoxaSa** [comment]
How do I install the developer version with the bug fixed?

**Comment by AntoxaSa** [comment]
installed the version by the developer, now the error is:
Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 862, in async_setup_platform
    air_fresh = AirFresh(host, token, model=model)
TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by syssi** [comment]
Uh. My fault. I prepare a fix and make a release for easy installation via HACS.

**Comment by syssi** [comment]
Hmm. The code is fine. It looks like your `python-miio` version is outdated. Do you use other xiaomi miio devices which requires an old `python-miio` version?

**Comment by AntoxaSa** [comment]
how to update the version? Home asistent has been updated to the freshest one.

**Comment by syssi** [comment]
I know what's going on. The required `python-miio` part isn't released right now. A new `python-miio` release is needed first.

**Comment by AntoxaSa** [comment]
![HA](https://user-images.githubusercontent.com/71827946/97836278-c279d500-1cfd-11eb-85d5-21fe77f45ff4.jpg)

**Comment by syssi** [comment]
Unfortunately you have to wait a bit. Updating requirements to the development version isn't easy.

**Comment by AntoxaSa** [comment]
Ok, let's wait. The main thing is that the problem is clear to you

**Comment by syssi** [comment]
It is. Please ping me if there is no progress here.

**Comment by AntoxaSa** [comment]
As I understand it, we are waiting for the release of python-miio 5.4?

**Comment by syssi** [comment]
Correct.
